# Generated by Django 3.2.4 on 2021-06-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20210621_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='finish_time',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='match',
            name='start_time',
            field=models.CharField(max_length=5),
        ),
    ]
