# Generated by Django 3.2.4 on 2021-06-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20210621_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='parking',
            field=models.BooleanField(),
        ),
    ]
