# Generated by Django 3.2.4 on 2021-06-23 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0005_alter_gym_shower'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gym',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gyms', to=settings.AUTH_USER_MODEL),
        ),
    ]
