# Generated by Django 3.2.4 on 2021-06-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_auto_20210623_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
